Repository codesquad-member-2020/dust-2, pull requests merged in 2020-04, with the labels that each got.

#18 MVC 구조에 맞게 리팩토링
  client-mobile/DustApp/DustApp/Assets.xcassets/densityLabelColor-covered.colorset/Contents.json
  client-mobile/DustApp/DustApp/Assets.xcassets/densityLabelColor.colorset/Contents.json
  client-mobile/DustApp/DustApp/Views/Dust/DustInfoCell.swift
  client-mobile/DustApp/DustApp/Views/Dust/DustStatusView.swift
Labels: Refactoring, iOS

#20 미세먼지 정보 View
  client-web/.babelrc
  client-web/.gitignore
  client-web/assets/bad.png
  client-web/assets/good.png
  client-web/assets/normal.png
  client-web/assets/worst.png
  client-web/constants/emojis.js
  client-web/display.css
  client-web/dust.html
  client-web/package-lock.json
  client-web/package.json
  client-web/src/dust-display/index.js
  client-web/webpack.config.js
Labels: frontend

#22 스와이프(Swipe) 기능 구현
  client-web/dust.html
  client-web/src/swipe/index.js
  client-web/style/display.css
  client-web/style/reset.css
  client-web/style/swipe.css
Labels: frontend

#24 네트워크 매니저 클래스
  client-mobile/DustApp/DustApp.xcodeproj/project.pbxproj
  client-mobile/DustApp/DustApp/Base.lproj/Main.storyboard
  client-mobile/DustApp/DustApp/Models/Dust/DustInfo.swift
  client-mobile/DustApp/DustApp/Models/Dust/NetworkManager.swift
  client-mobile/DustApp/DustApp/Models/Dust/Station.swift
  client-mobile/DustApp/DustApp/ViewControllers/DustViewController.swift
  client-mobile/DustApp/DustApp/Views/Dust/DustStatusView.swift
Labels: enhancement, iOS

#28 미세먼지 예보 View
  client-web/dust.html
  client-web/src/dust-display/scroll.js
  client-web/src/dust-forecast/index.js
  client-web/src/swipe/change.js
  client-web/style/display.css
  client-web/style/forecast.css
  client-web/style/nav.css
  client-web/style/reset.css
  client-web/style/swipe.css
Labels: frontend

#30 예보 뷰 컨트롤러 UI 인터랙션 구현
  client-mobile/DustApp/DustApp.xcodeproj/project.pbxproj
  client-mobile/DustApp/DustApp/Assets.xcassets/stop.fill.symbolset/Contents.json
  client-mobile/DustApp/DustApp/Assets.xcassets/stop.fill.symbolset/stop.fill.svg
  client-mobile/DustApp/DustApp/Base.lproj/Main.storyboard
  client-mobile/DustApp/DustApp/ViewControllers/ForecastViewController.swift
  client-mobile/DustApp/DustApp/ViewModel/ForecastVIewModel.swift
  client-mobile/DustApp/DustApp/Views/Forecast/ForecastImageSlider.swift
  client-mobile/DustApp/DustApp/Views/Forecast/ForecastImageView.swift
  client-mobile/DustApp/DustApp/Views/Forecast/TogglePlayingButton.swift
Labels: enhancement, iOS

#31 예보 이미지 데이터 요청 및 뷰모델 구조
  client-mobile/DustApp/DustApp.xcodeproj/project.pbxproj
  client-mobile/DustApp/DustApp/Assets.xcassets/SystemBlack.colorset/Contents.json
  client-mobile/DustApp/DustApp/Assets.xcassets/pause.fill.symbolset/Contents.json
  client-mobile/DustApp/DustApp/Assets.xcassets/pause.fill.symbolset/pause.fill.svg
  client-mobile/DustApp/DustApp/Base.lproj/Main.storyboard
  client-mobile/DustApp/DustApp/Models/Forecast/ForecastNetworkManager.swift
  client-mobile/DustApp/DustApp/ViewControllers/ForecastViewController.swift
  client-mobile/DustApp/DustApp/ViewModel/ForecastVIewModel.swift
  client-mobile/DustApp/DustApp/Views/Forecast/ForecastImageView.swift
  client-mobile/DustApp/DustApp/Views/Forecast/TogglePlayingButton.swift
Labels: enhancement, iOS

#33 DustStatusView Label attributedString 수정 및 indicatorView 추가
  client-mobile/DustApp/DustApp.xcodeproj/project.pbxproj
  client-mobile/DustApp/DustApp/Base.lproj/Main.storyboard
  client-mobile/DustApp/DustApp/Views/Dust/DustStatusView.swift
  client-mobile/DustApp/DustApp/Views/Dust/StatusLoadingView.swift
Labels: enhancement, iOS

#38 미세먼지 리스트 뷰컨 뷰모델 적용 및 mockup 데이터 매니저 구현
  client-mobile/DustApp/DustApp.xcodeproj/project.pbxproj
  client-mobile/DustApp/DustApp/Base.lproj/Main.storyboard
  client-mobile/DustApp/DustApp/Extensions/DateCalculator.swift
  client-mobile/DustApp/DustApp/Models/Dust/DustInfoListDataSource.swift
  client-mobile/DustApp/DustApp/Models/Dust/MockupDustNetworkManager.swift
  client-mobile/DustApp/DustApp/ViewControllers/DustViewController.swift
  client-mobile/DustApp/DustApp/ViewModel/DustStatusViewModel.swift
  client-mobile/DustApp/DustApp/Views/Dust/DustInfoCell.swift
  client-mobile/DustApp/DustApp/Views/Dust/DustInfoListDelegate.swift
  client-mobile/DustApp/DustApp/Views/Dust/DustStatusView.swift
Labels: enhancement, iOS

#36 서버 데이터 요청 및 리펙토링
  client-web/constants/api.js
  client-web/constants/chart.js
  client-web/constants/colors.js
  client-web/constants/grade.js
  client-web/dust.html
  client-web/package-lock.json
  client-web/package.json
  client-web/src/dust-display/chart/chart.js
  client-web/src/dust-display/chart/chartOption.js
  client-web/src/dust-display/event/scroll.js
  client-web/src/dust-display/index.js
  client-web/src/dust-display/scroll.js
  client-web/src/dust-display/style/display.css
  client-web/src/dust-display/style/reset.css
  client-web/src/dust-display/view/index.js
  client-web/src/dust-forecast/event/index.js
  client-web/src/dust-forecast/index.js
  client-web/src/dust-forecast/style/forecast.css
  client-web/src/dust-forecast/view/index.js
  client-web/src/fetch/index.js
  client-web/src/nav/event/change.js
  client-web/src/nav/index.js
  client-web/src/nav/style/nav.css
  client-web/src/nav/view/index.js
  client-web/src/swipe/change.js
  client-web/src/swipe/index.js
  client-web/style/nav.css
  client-web/style/swipe.css
  client-web/webpack.config.js
Labels: fe리뷰요청, frontend

#34 실제 예보 정보로 수정
  backend/src/main/java/dust2/backend/api/DustApiController.java
  backend/src/main/java/dust2/backend/config/SwaggerConfig.java
  backend/src/main/java/dust2/backend/config/WebConfig.java
  backend/src/main/java/dust2/backend/domain/Forecast.java
  backend/src/main/java/dust2/backend/util/DateUtils.java
  backend/src/main/java/dust2/backend/util/ForecastApiUtils.java
Labels: backend, enhancement

#42 Hotfix: 시간 계산 수정
  client-mobile/DustApp/DustApp/Extensions/DateCalculator.swift
  client-mobile/DustApp/DustApp/Views/Dust/DustStatusView.swift
Labels: iOS

#46 [#45] 서버에서 데이터 받아오는 부분을 실서버로 이동
  client-web/constants/api.js
  client-web/package.json
  client-web/src/dust-display/event/scroll.js
  client-web/src/dust-display/index.js
  client-web/src/dust-display/view/index.js
  client-web/src/dust-forecast/index.js
  client-web/src/dust-forecast/style/forecast.css
Labels: frontend

#47 Station 네트워크 요청
  client-mobile/DustApp/DustApp.xcodeproj/project.pbxproj
  client-mobile/DustApp/DustApp/Info.plist
  client-mobile/DustApp/DustApp/Models/Dust/DustNetworkManager.swift
  client-mobile/DustApp/DustApp/Models/Dust/MockupDustNetworkManager.swift
  client-mobile/DustApp/DustApp/Models/Dust/NetworkManager.swift
  client-mobile/DustApp/DustApp/Models/Dust/Station.swift
  client-mobile/DustApp/DustApp/Models/Dust/StationInfo.swift
  client-mobile/DustApp/DustApp/ViewControllers/DustViewController.swift
  client-mobile/DustApp/DustApp/ViewModel/DustStatusViewModel.swift
Labels: iOS

#52 CSS 수정
  client-web/src/dust-display/chart/chart.js
  client-web/src/dust-display/event/scroll.js
  client-web/src/dust-display/view/index.js
  client-web/src/dust-forecast/style/forecast.css
Labels: frontend

#53 미세먼지 예보 이미지 요청 서버 연결
  client-mobile/DustApp/DustApp.xcodeproj/project.pbxproj
  client-mobile/DustApp/DustApp/Base.lproj/Main.storyboard
  client-mobile/DustApp/DustApp/Models/Forecast/Forecast.swift
  client-mobile/DustApp/DustApp/Models/Forecast/ForecastNetworkManager.swift
  client-mobile/DustApp/DustApp/ViewControllers/ForecastViewController.swift
  client-mobile/DustApp/DustApp/ViewModel/ForecastVIewModel.swift
Labels: enhancement, iOS

#55 [Hotfix] JSON key값 수정
  client-mobile/DustApp/DustApp/Models/Dust/DustInfo.swift
Labels: iOS

#62 예보 이미지 요청 에러 해결
  client-mobile/DustApp/DustApp/ViewModel/ForecastVIewModel.swift
Labels: bug, iOS

#64 이미지 재생 애니메이션 비동기 처리
  client-mobile/DustApp/DustApp/Views/Forecast/ForecastImageView.swift
Labels: Refactoring, iOS
